### Import Librares

In [1]:
import numpy as np
import pandas as pd



### Input Example Data

In [3]:
# Define the variables and the target correlation matrix
variables = [
    'avg_rating', 'number_of_viewers', 'budget', 'popularity',
    'revenue', 'vote_average', 'vote_count'
]

In [2]:
# The correlation matrix
# Note: Since it's symmetric, we can input it as a list of lists or a 2D array.
correlation_matrix = np.array([
    [1.000, 0.127, -0.092, 0.061, 0.003, 0.531, 0.099],
    [0.127, 1.000, 0.285, 0.551, 0.441, 0.284, 0.623],
    [-0.092, 0.285, 1.000, 0.520, 0.763, 0.001, 0.620],
    [0.061, 0.551, 0.520, 1.000, 0.636, 0.261, 0.794],
    [0.003, 0.441, 0.763, 0.636, 1.000, 0.140, 0.782],
    [0.531, 0.284, 0.001, 0.261, 0.140, 1.000, 0.299],
    [0.099, 0.623, 0.620, 0.794, 0.782, 0.299, 1.000]
])

### Setup Synthetic Inputs

In [4]:
# For synthetic data generation, we assume the variables are standardized (mean=0, std=1).
# In this case, the covariance matrix IS the correlation matrix.
covariance_matrix = correlation_matrix

In [6]:
# Number of rows (samples) to generate
num_samples = 500

# Mean vector (assuming standardized variables)
mean_vector = np.zeros(len(variables))

### --- Method 1: Using numpy.random.multivariate_normal (Direct Approach) ---

In [ ]:
print("--- Generating Data with Method 1 (multivariate_normal) ---")

# The function handles the transformation process internally
synthetic_data_direct = np.random.multivariate_normal(
    mean=mean_vector,
    cov=covariance_matrix,
    size=num_samples
)

# Convert to a Pandas DataFrame for better visualization
df_direct = pd.DataFrame(synthetic_data_direct, columns=variables)

print("\nFirst 10 rows of generated data (direct approach):")
print(df_direct.head(10))





--- Generating Data with Method 1 (multivariate_normal) ---

First 10 rows of generated data (direct approach):
   avg_rating  number_of_viewers    budget  popularity   revenue  \
0    0.752462          -0.017600  0.016270   -0.933595  0.172398   
1   -0.666010          -0.352408  0.049517   -0.318137 -0.360542   
2    1.316752          -1.706554 -1.156645   -0.469564 -1.409961   
3    1.231010           0.328513 -0.691328    0.817307  0.065162   
4   -0.172614          -0.492323  0.491680    0.405670  0.499307   
5    0.180331          -1.360609 -1.727888   -2.499070 -0.811765   
6    0.360157           0.460071 -0.538266    1.392307 -0.243260   
7   -0.034513           0.933163  0.432381    0.165638  0.114859   
8   -0.143541           0.222349 -1.343622   -1.105713 -1.062584   
9    1.101322           0.610908  0.918062    1.279851  0.889341   

   vote_average  vote_count  
0      1.220050    0.217837  
1     -1.327953   -0.849934  
2      0.327756   -1.009396  
3     -0.463666    

In [19]:
# Verify the result
corr_m1 = df_direct.corr()

# print("\nCalculated Correlation Matrix (should be close to target):")
print(corr_m1)

                   avg_rating  number_of_viewers    budget  popularity  \
avg_rating           1.000000           0.151602 -0.098045    0.026688   
number_of_viewers    0.151602           1.000000  0.295497    0.568484   
budget              -0.098045           0.295497  1.000000    0.508836   
popularity           0.026688           0.568484  0.508836    1.000000   
revenue              0.006627           0.446487  0.804052    0.605946   
vote_average         0.496051           0.321100  0.030369    0.248945   
vote_count           0.066837           0.643921  0.640047    0.792045   

                    revenue  vote_average  vote_count  
avg_rating         0.006627      0.496051    0.066837  
number_of_viewers  0.446487      0.321100    0.643921  
budget             0.804052      0.030369    0.640047  
popularity         0.605946      0.248945    0.792045  
revenue            1.000000      0.161535    0.772642  
vote_average       0.161535      1.000000    0.310655  
vote_count     

### --- Method 2: Using Cholesky Decomposition (Illustrative Approach) ---

In [10]:

print("\n--- Generating Data with Method 2 (Cholesky Decomposition) ---")

# Step 1: Generate uncorrelated (white noise) standard normal random data
uncorrelated_data = np.random.randn(num_samples, len(variables))
uncorrelated_data



--- Generating Data with Method 2 (Cholesky Decomposition) ---


array([[-0.39804139,  0.75023938, -0.53851391, ...,  0.97569721,
        -0.52788845,  1.59044612],
       [-0.3703047 ,  2.25327139, -1.00354304, ..., -0.46989696,
         0.05311834, -0.06145138],
       [-0.47289764, -0.85370379,  1.95928978, ...,  0.37465957,
         0.13744667, -0.41996832],
       ...,
       [ 0.91260013, -0.02495429,  1.54295681, ...,  0.52580009,
        -0.23507157,  1.72275938],
       [-0.08854872,  0.25458196,  1.02816393, ...,  0.41009124,
         0.1568022 , -0.24582711],
       [-0.20578239,  1.97084754,  0.07481297, ..., -1.84403135,
         1.88411978, -1.02525825]], shape=(500, 7))

In [12]:
# 

# Step 2: Calculate the Cholesky decomposition of the target covariance matrix
# This finds a lower triangular matrix 'L' such that L * L^T = covariance_matrix
try:
    L = np.linalg.cholesky(covariance_matrix)
    print("\nCholesky decomposition (Lower triangular matrix L):")
    print(L)
except np.linalg.LinAlgError:
    print("\nError: The provided covariance matrix is not positive-definite. Cholesky decomposition failed.")
    # Exit or use a different generation method if this fails
    exit()




Cholesky decomposition (Lower triangular matrix L):
[[ 1.          0.          0.          0.          0.          0.
   0.        ]
 [ 0.127       0.99190272  0.          0.          0.          0.
   0.        ]
 [-0.092       0.29910595  0.94977452  0.          0.          0.
   0.        ]
 [ 0.061       0.54768778  0.3809276   0.74243603  0.          0.
   0.        ]
 [ 0.003       0.44421594  0.6637453   0.18814611  0.57158238  0.
   0.        ]
 [ 0.531       0.21833089 -0.01626919  0.15520425  0.04027147  0.80274267
   0.        ]
 [ 0.099       0.61541015  0.46856928  0.36692374  0.22443321  0.06690167
   0.4499256 ]]


In [14]:
# Step 3: Transform the uncorrelated data using the decomposition matrix L
# The dot product applies the desired correlation structure
# 
correlated_data = uncorrelated_data.dot(L.T)
correlated_data



array([[-0.39804139,  0.69361323, -0.25044593, ...,  0.41225566,
        -0.52231464,  0.8350438 ],
       [-0.3703047 ,  2.18799732, -0.2451047 , ...,  0.1110723 ,
         0.37325562,  0.8398062 ],
       [-0.47289764, -0.90684911,  1.64904221, ...,  1.11444582,
        -0.36005853,  0.21211764],
       ...,
       [ 0.91260013,  0.09114799,  1.37403787, ...,  1.15234162,
         0.15124361,  1.35557249],
       [-0.08854872,  0.24127485,  1.06081736, ...,  1.16039026,
         0.24206129,  0.87654047],
       [-0.20578239,  1.92875467,  0.67947965, ..., -0.44471468,
         1.49798144, -0.13628322]], shape=(500, 7))

In [16]:
# Step 4: Add the mean vector (assuming 0 mean for this example)
synthetic_data_cholesky = correlated_data + mean_vector
synthetic_data_cholesky



array([[-0.39804139,  0.69361323, -0.25044593, ...,  0.41225566,
        -0.52231464,  0.8350438 ],
       [-0.3703047 ,  2.18799732, -0.2451047 , ...,  0.1110723 ,
         0.37325562,  0.8398062 ],
       [-0.47289764, -0.90684911,  1.64904221, ...,  1.11444582,
        -0.36005853,  0.21211764],
       ...,
       [ 0.91260013,  0.09114799,  1.37403787, ...,  1.15234162,
         0.15124361,  1.35557249],
       [-0.08854872,  0.24127485,  1.06081736, ...,  1.16039026,
         0.24206129,  0.87654047],
       [-0.20578239,  1.92875467,  0.67947965, ..., -0.44471468,
         1.49798144, -0.13628322]], shape=(500, 7))

In [ ]:
# Convert to a Pandas DataFrame
df_cholesky = pd.DataFrame(synthetic_data_cholesky, columns=variables)
print("\nFirst 10 rows of generated data (Cholesky approach):")
print(df_cholesky.head(10))


,avg_rating,number_of_viewers,budget,popularity,revenue,vote_average,vote_count
0,-0.398041,0.693613,-0.250446,-0.292337,0.412256,-0.522315,0.835044
1,-0.370305,2.187997,-0.245105,1.010450,0.111072,0.373256,0.839806
2,-0.472898,-0.906849,1.649042,0.172891,1.114446,-0.360059,0.212118
3,-0.156138,0.677889,-0.512813,-0.822439,-1.409750,-0.333640,-1.431506
4,1.312757,1.556031,-0.568297,0.286499,0.694943,0.912173,1.051583
...,...,...,...,...,...,...,...
495,0.808356,-0.673432,0.562971,-0.274989,-0.900095,-0.124582,-0.471945
496,-0.312150,0.473472,-0.223949,2.339041,0.169596,1.093123,1.060706
497,0.912600,0.091148,1.374038,-0.017317,1.152342,0.151244,1.355572
498,-0.088549,0.241275,1.060817,1.041541,1.160390,0.242061,0.876540


In [20]:
# Verify the result
corr_m2 = df_cholesky.corr()

# print("\nCalculated Correlation Matrix (should be close to target):")
print(corr_m2)



                   avg_rating  number_of_viewers    budget  popularity  \
avg_rating           1.000000           0.141592 -0.051683    0.044598   
number_of_viewers    0.141592           1.000000  0.256260    0.549578   
budget              -0.051683           0.256260  1.000000    0.494045   
popularity           0.044598           0.549578  0.494045    1.000000   
revenue              0.023332           0.417487  0.735693    0.614054   
vote_average         0.510483           0.275917 -0.017530    0.256285   
vote_count           0.115647           0.594984  0.620970    0.787782   

                    revenue  vote_average  vote_count  
avg_rating         0.023332      0.510483    0.115647  
number_of_viewers  0.417487      0.275917    0.594984  
budget             0.735693     -0.017530    0.620970  
popularity         0.614054      0.256285    0.787782  
revenue            1.000000      0.118753    0.756549  
vote_average       0.118753      1.000000    0.301417  
vote_count     

In [21]:
# --- ACCURACY CALCULATION (Mean Absolute Error) ---
# We calculate the average difference between the Target and Synthetic cells
mae_m1 = np.mean(np.abs(correlation_matrix - corr_m1))
mae_m2 = np.mean(np.abs(correlation_matrix - corr_m2))

print(f"Comparison Results (N={num_samples})")
print("-" * 35)
print(f"Method 1 MAE: {mae_m1:.6f}")
print(f"Method 2 MAE: {mae_m2:.6f}")
print("-" * 35)
print(f"Difference: {abs(mae_m1 - mae_m2):.6f}")

Comparison Results (N=500)
-----------------------------------
Method 1 MAE: 0.016956
Method 2 MAE: 0.015238
-----------------------------------
Difference: 0.001718
